[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "mypkg"
packages = [
    { include = "mypkg", from = "src" },
]
version = "0.1.0"
authors = []

[tool.poetry.dependencies]
python = "^3.7"
click = "*"

[tool.poetry.scripts]
cli = 'mypkg:cli.main'
