[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "mypkg"
author = ""
author-email = ""
license = "..."
keywords = ""
classifiers = []
requires = [
  "click"
]

[tool.flit.scripts]
cli = 'mypkg:cli.main'
